export default function Head() {
  return (
    <>
      <title>vYear Progress</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@viistorrr" />
      <meta name="twitter:creator" content="@viistorrr" />
      <meta name="twitter:title" content="vYear Progress" />
      <meta name="twitter:description" content="A simple year progress bar" />
      <meta
        name="twitter:image"
        content="https://vyear-progress.vercel.app/preview.png"
      />

      <meta property="og:type" content="website" />
      <meta property="og:title" content="vYear Progress" />
      <meta property="og:description" content="A simple year progress bar" />
      <meta
        property="og:image"
        content="https://vyear-progress.vercel.app/preview.png"
      />
      <meta property="og:url" content="https://vyear-progress.vercel.app/" />
      <meta property="og:site_name" content="vYear Progress" />
      <meta property="og:locale" content="en_US" />
    </>
  );
}
